# Production environment configuration for Auth Service
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key-id: ${JWT_KEY_ID:auth-service-key}
#  key-id: auth-service-key

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}