# GATEWAY-DEV

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bus-service-bus
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/api/v1/buses/**

            - id: bus-service-trip
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/api/v1/trips/**

            - id: bus-service-driver
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/api/v1/drivers/**

            - id: bus-service-conductor
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/api/v1/conductors/**

            - id: bus-service-route
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/api/v1/routes/**

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
               - Path=/api/v1/auth/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG